export const LOG_FORMAT = "%-15s%-15s%-40s%-40s";
export const LOG_TASK_ID_PREFIX = " Task ID: ";

export const WHITE_SPACES = "(\\s*)";
export const REGEX_QUOTES = "['\"`"]";

export const CLOUD_URLS_REGEX = /([\w]+[.]){1,10}(s3\.amazonaws\.com|rds\.amazonaws\.com|cache\.amazonaws\.com|blob\.core\.windows\.net|onedrive\.live\.com|1drv\.com|storage\.googleapis\.com|storage\.cloud\.google\.com|storage-download\.googleapis\.com|content-storage-upload\.googleapis\.com|content-storage-download\.googleapis\.com|cloudfront\.net|digitaloceanspaces\.com|oraclecloud\.com|aliyuncs\.com|firebaseio\.com|rackcdn\.com|objects\.cdn\.dream\.io|objects-us-west-1\.dream\.io)/gim;

export const SECRETS_REGEX = /['\"`]?\w*(?:\s*)(secret|token|password|passwd|authorization|bearer|aws_access_key_id|aws_secret_access_key|irc_pass|SLACK_BOT_TOKEN|id_dsa|secret[_-]?(?:key|token|secret)|api[_-]?(?:key|token|secret)|access[_-]?(?:key|token|secret)|auth[_-]?(?:key|token|secret)|session[_-]?(?:key|token|secret)|consumer[_-]?(?:key|token|secret)|public[_-]?(?:key|token|secret)|client[_-]?(?:id|token|key)|ssh[_-]?key|encrypt[_-]?(?:secret|key)|decrypt[_-]?(?:secret|key)|github[_-]?(?:key|token|secret)|slack[_-]?token)\w*(?:\s*)['\"`]?\s*[:=]+[:=>]?\s*['\"`]\s*(?<secret>[\w\-/~!@#$%^&*+]+)\s*['\"`]/gim;

export const HTTP_BASIC_AUTH_SECRETS = /Authorization.{0,5}Basic(\s*)([A-Za-z0-9+/=]+)/gim;

export const B64_SOURCE_MAP_REGEX = /sourceMappingURL=data(.*)json(.*)base64,((?:[a-z0-9+/]{4})*(?:[a-z0-9+/]{2}==|[a-z0-9+/]{3}=)?)(\\n)?/gim;

export const EXTRACT_DEPENDENCIES_REGEX = /dependencies([a-z-_0-9])*['\"`]:\{(.*?)\}/gim;

export const EXTRACT_FROM_NODE_MODULES = /\/node_modules\/(@?[a-z-_.0-9]+)/gim;

export const ENDPOINTS_GET_REGEX = /\.[\$]?get\(['\"`]?(.*?)['\"`]?\)/gim;
export const ENDPOINTS_POST_REGEX = /\.[\$]?post\(['\"`]?(.*?)['\"`]?\)/gim;
export const ENDPOINTS_PUT_REGEX = /\.[\$]?put\(['\"`]?(.*?)['\"`]?\)/gim;
export const ENDPOINTS_DELETE_REGEX = /\.[\$]?delete\(['\"`]?(.*?)['\"`]?\)/gim;
export const ENDPOINTS_PATCH_REGEX = /\.[\$]?patch\(['\"`]?(.*?)['\"`]?\)/gim;

export const SCAN_ISSUE_HEADER = "This issue was generated by \"JS Miner\" Chrome extension.<br><br>";

export const CONFIDENCE_CERTAIN = "Certain";
export const CONFIDENCE_TENTATIVE = "Tentative";
export const CONFIDENCE_FIRM = "Firm";
export const SEVERITY_INFORMATION = "Information";
export const SEVERITY_MEDIUM = "Medium";
export const SEVERITY_HIGH = "High";

export const HTML_LIST_OPEN = '<ul>';
export const HTML_LIST_BULLET_OPEN = '<li> ';
export const HTML_LIST_BULLET_CLOSED = '</li>';
export const HTML_LIST_CLOSED = '</ul>';
